### ISSUE TITLE
DNS broke

### ISSUE THREAD

**Issue by leebaird** [L1ghtn1ng/Egress-Assess#1]
Kali 1
./Egress-Assess.py --server dns

Kali 2
./Egress-Assess.py --client dns --ip <IP> --file /tmp/secret.txt

```
Traceback (most recent call last):
  File "./Egress-Assess.py", line 100, in <module>
    proto_module.transmit(file_data)
  File "protocols/clients/dns_client.py", line 71, in transmit
    encoded_data = base64.b64encode(str(struct.pack('>I', packet_number)) + ".:|:." + data_to_transmit[byte_reader:byte_reader + self.length])
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by L1ghtn1ng** [comment]
I have added support for server port/client ports for this, still working on trying to get it to work though
