### ISSUE TITLE
SFTP broke

### ISSUE THREAD

**Issue by leebaird** [L1ghtn1ng/Egress-Assess#10]
Kali 1
./Egress-Assess.py --server sftp --server-port 8000 --username lee --password hack

Kali 2
./Egress-Assess.py --client sftp --client-port 8000 --username lee --password hack --ip 192.168.1.5 --file /tmp/secret.txt

[*] Transmitting data...
Unknown exception: Raw
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2199, in _negotiate_keys
    self.kex_engine.start_kex()
  File "/usr/lib/python3/dist-packages/paramiko/kex_curve25519.py", line 54, in start_kex
    serialization.Encoding.Raw, serialization.PublicFormat.Raw
  File "/usr/lib/python3.8/enum.py", line 352, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

Traceback (most recent call last):
  File "./Egress-Assess.py", line 100, in <module>
    proto_module.transmit(file_data)
  File "protocols/clients/sftp_client.py", line 57, in transmit
    transport.connect(username=self.username, password=self.password)
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1291, in connect
    self.start_client()
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2199, in _negotiate_keys
    self.kex_engine.start_kex()
  File "/usr/lib/python3/dist-packages/paramiko/kex_curve25519.py", line 54, in start_kex
    serialization.Encoding.Raw, serialization.PublicFormat.Raw
  File "/usr/lib/python3.8/enum.py", line 352, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

**Comment by leebaird** [comment]
duplicate
